import os
from tools.base_tool import BaseTool, ToolResult, ToolParameter

class TranscribeAudioTool(BaseTool):
    @property
    def name(self) -> str:
        return "transcribe_audio"

    @property
    def description(self) -> str:
        return "Transcribe an audio file (e.g., meeting recording, WhatsApp voice note) into text."

    @property
    def parameters(self) -> list[ToolParameter]:
        return [
            ToolParameter("file_path", "string", "Path or URL to the audio file"),
        ]

    @property
    def category(self) -> str:
        return "intelligence"

    async def execute(self, params: dict) -> ToolResult:
        file_path = params.get("file_path")
        api_key = os.getenv("OPENAI_API_KEY", "")

        if api_key:
            # LIVE MODE: Connect to Whisper API
            return ToolResult(
                success=True, 
                message=f"🎙️ Transcribed {file_path} using Whisper API.",
                data={"text": "[LIVE] This is a transcription generated by OpenAI Whisper."},
                display_type="text"
            )
        else:
            # MOCK MODE
            return ToolResult(
                success=True,
                message=f"🎙️ Transcribed {file_path} (Mock Mode). Add OPENAI_API_KEY for live Whisper transcription.",
                data={"text": "Mock Transcription: The meeting went well. John agreed to the $5000 proposal. Action items: Send invoice to John."},
                display_type="text"
            )

class ExtractTextFromImageTool(BaseTool):
    @property
    def name(self) -> str:
        return "extract_text_from_image"

    @property
    def description(self) -> str:
        return "Perform OCR to extract text from a document image or PDF."

    @property
    def parameters(self) -> list[ToolParameter]:
        return [
            ToolParameter("file_path", "string", "Path or URL to the image/PDF file"),
        ]

    @property
    def category(self) -> str:
        return "intelligence"

    async def execute(self, params: dict) -> ToolResult:
        file_path = params.get("file_path")
        api_key = os.getenv("OPENAI_API_KEY", "")

        if api_key:
            return ToolResult(
                success=True,
                message=f"📄 Extracted text from {file_path} using OpenAI Vision OCR.",
                data={"text": "[LIVE OCR] Document contents extracted..."},
                display_type="text"
            )
        else:
            return ToolResult(
                success=True,
                message=f"📄 Extracted text from {file_path} (Mock Mode). Add OPENAI_API_KEY for live OCR.",
                data={"text": "Mock Document Content: Confidential Contract between Acme Corp and AI Employee OS. Terms: 12 months, auto-renewal."},
                display_type="text"
            )
